version: "3.1"
#
services:
  nginx:
    image: kbase/nginx:latest
    command:
      - "-template"
      - "/kb/deployment/conf/.templates/nginx.conf.templ:/etc/nginx/nginx.conf"
      - "-env"
      - "https://raw.githubusercontent.com/kbase/mini_kb/master/deployment/conf/nginx-minikb.ini"
      - "nginx" 
    ports:
      - "8000:80"
    depends_on: ["auth2", "handle_service", "handle_manager", "workspace", "shock"]

  workspace:
    image: kbase/kb_workspace:develop
    command:
      - "-template"
      - "/kb/deployment/conf/.templates/deployment.cfg.templ:/kb/deployment/conf/deployment.cfg"
      - "-env"
      - "https://raw.githubusercontent.com/kbase/mini_kb/master/deployment/conf/workspace-minikb.yml"
      - "-wait"
      - "tcp://ci-mongo:27017"
      - "-wait"
      - "tcp://db-init:8080"
      - "-wait"
      - "tcp://auth2:8080"
      - "-timeout"
      - "150s"
      - "-stdout"
      - "/kb/deployment/services/workspace/glassfish_domain/Workspace/logs/server.log"
      - "/kb/deployment/bin/start_workspace.sh"
    #ports:
    #  - "7058:7058"
    depends_on: ["auth2", "handle_service", "handle_manager", "ci-mongo","db-init"]
  
  shell:
    image: kbase/db_initialize
    entrypoint: [ "/bin/bash"]
    stdin_open: true
    tty: true
    volumes:
      - .:/home/workspace_deluxe
  
  handle_service:
    image: kbase/handle_service:latest
    command: [ "https://raw.githubusercontent.com/kbase/mini_kb/master/deployment/conf/handle_service-minikb.yml"]
    #ports:
    #  - "7109:7109"
    depends_on: ["handle_manager", "ci-mysql", "shock", "auth2","db-init"]

  shock:
    image: kbase/kb_shock:develop
    command:
      - "-template"
      - "/kb/deployment/conf/.templates/shock-server.cfg.templ:/kb/deployment/conf/shock-server.cfg"
      - "-env"
      - "https://raw.githubusercontent.com/kbase/mini_kb/master/deployment/conf/shock-minikb.yml"
      - "-wait"
      - "tcp://ci-mongo:27017"
      - "-wait"
      - "tcp://db-init:8080"
      - "-wait"
      - "tcp://auth2:8080"
      - "-timeout"
      - "150s"
      - "/kb/deployment/bin/shock-server"
      - "--conf"
      - "/kb/deployment/conf/shock-server.cfg"
    #ports:
    #  - "7044:7044"
    depends_on: ["ci-mongo", "db-init", "auth2"]

  handle_manager:
    image: kbase/handle_mngr:latest
    command:
      - "-template"
      - "/kb/deployment/conf/.templates/deployment.cfg.templ:/kb/deployment/conf/deployment.cfg"
      - "-env"
      - "https://raw.githubusercontent.com/kbase/mini_kb/master/deployment/conf/handle_mngr-minikb.yml"
      - "-wait"
      - "tcp://auth2:8080"
      - "-timeout"
      - "150s"
      - "starman"
      - "--listen"
      - ":9001"
      - "/kb/deployment/lib/Bio/KBase/HandleMngr/HandleMngr.psgi"
    #ports:
    #  - "9001:9001"
    depends_on: ["auth2","db-init"]

  auth2:
    image: kbase/kb_auth2:develop
    command:
      - "-wait"
      - "tcp://ci-mongo:27017"
      - "-wait"
      - "tcp://db-init:8080"
      - "-timeout"
      - "120s"
      - "-template"
      - "/kb/deployment/conf/.templates/deployment.cfg.templ:/kb/deployment/conf/deployment.cfg"
      - "-env"
      - "https://raw.githubusercontent.com/kbase/mini_kb/master/deployment/conf/auth2-minikb.yml"
      - "/kb/deployment/bin/start_auth2.sh"
    #ports:
    #  - "8080:8080"
    depends_on: ["ci-mongo","db-init"]

  db-init:
    image: kbase/db_initialize
    volumes:
      - ./mysqldump:/mnt/mysqldump
      - ./ws.mongodump:/mnt/ws.mongodump
      - ./bin:/mnt/bin
    entrypoint:
      - /kb/deployment/bin/dockerize.sh
      - -wait
      - tcp://ci-mysql:3306/
      - -wait
      - tcp://ci-mongo:27017
      - -timeout
      - 120s
      - /mnt/bin/initialize_all.sh
    depends_on: ['ci-mysql','ci-mongo']

  ci-mongo:
    image: mongo:2
    #ports:
    #  - "27017:27017"
    command: --smallfiles
  
  ci-mysql:
    image: mysql:5.5
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    #ports:
    #  - "3306:3306"
