version: "3.1"
#
services:
  workspace:
    image: kbase/kb_workspace:${TRAVIS_BRANCH:-latest}
    command: [ "https://raw.githubusercontent.com/kbase/mini_kb/master/deployment/conf/workspace-minikb.yml"]
    ports:
      - "7058:7058"
    depends_on: ["auth2", "handle_service", "handle_manager", "ci-mongo"]
  
  shell:
    image: ubuntu:latest
    entrypoint: [ "/bin/bash"]
    stdin_open: true
    tty: true
    volumes:
      - .:/home/workspace_deluxe
  
  handle_service:
    image: kbase/handle_service:latest
    command: [ "https://raw.githubusercontent.com/kbase/mini_kb/master/deployment/conf/handle_service-minikb.yml"]
    ports:
      - "7109:7109"
    depends_on: ["handle_manager", "ci-mysql", "shock", "auth2"]

  shock:
    image: kbase/kb_shock:develop
    command: [ "https://raw.githubusercontent.com/kbase/mini_kb/master/deployment/conf/shock-minikb.yml"]
    ports:
      - "7044:7044"
    depends_on: ["ci-mongo"]

  handle_manager:
    image: kbase/handle_mngr:latest
    command: [ "https://raw.githubusercontent.com/kbase/mini_kb/master/deployment/conf/handle_mngr-minikb.yml"]
    ports:
      - "9001:9001"
    depends_on: ["auth2"]

  auth2:
    image: kbase/kb_auth2:latest
    command: [ "https://raw.githubusercontent.com/kbase/mini_kb/master/deployment/conf/auth2-minikb.yml"]
    ports:
      - "8080:8080"
    depends_on: ["ci-mongo"]

  mongoinit:
    image: mongo:2
    volumes:
      - ./ws.mongodump:/mnt/ws.mongodump
    entrypoint: [ "mongorestore", "--host", "ci-mongo", "/mnt/ws.mongodump" ]
    depends_on: [ "ci-mongo" ]
  
  ci-mongo:
    image: mongo:2
    ports:
      - "27017:27017"
    command: --smallfiles
  
  mysqlinit:
    image: mysql:5.5
    volumes:
      - ./mysqldump:/mnt/mysqldump
    entrypoint: [ "mysql", "-h", "ci-mysql", "-v", "-e", "source /mnt/mysqldump" ]
    depends_on: [ "ci-mysql" ]

  ci-mysql:
    image: mysql:5.5
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
